name: Två jobb

on: workflow_dispatch

jobs:
    forsta:
        runs-on: ubuntu-latest
        steps :
            - name: Skapa en fil
              run:
                echo "resultatet av mitt hårda arbete" > resultat.txt
                ls -la
            - name: Ladda upp
              uses: actions/upload-artifact@v4
              with:
                name: mitt-resultat
                path: resultat.txt

    andra:
        runs-on: ubuntu-latest
        needs: forsta
        steps:
            - name: Hämta filen
              uses: actions/download-artifact@v4
              with:
                name: mitt-resultat
                
            - name: Läs filen
              run: cat resultat.txt
