name: Två jobb

on: workflow_dispatch

jobs:
    forsta:
        runs-on: ubuntu-latest
        steps :
            - name: Skapa en fil
              run: |
                echo "resultatet av mitt hårda arbete" > resultat.txt
                ls -la

    andra:
        runs-on: ubuntu-latest
        steps:
            - name: Leta efter filen
              run:
                ls -la
                cat resultat.txt
